post_install() {
  [ -f /etc/ld.so.preload ] || touch /etc/ld.so.preload

  sed -i "/\/usr\/lib\/mali-egl\/libgbm-compat.so/d" /etc/ld.so.preload
  echo "/usr/lib/mali-egl/libgbm-compat.so" >> /etc/ld.so.preload

  sed -i "/\/usr\/lib\/mali-egl\/libmali.so/d" /etc/ld.so.preload
  echo "/usr/lib/mali-egl/libmali.so" >> /etc/ld.so.preload
}

post_remove() {
  sed -i "/\/usr\/lib\/mali-egl\/libgbm-compat.so/d" /etc/ld.so.preload
  sed -i "/\/usr\/lib\/mali-egl\/libmali.so/d" /etc/ld.so.preload
}