#!/bin/bash

PATH="/sbin:/usr/sbin:/bin:/usr/bin:$PATH"

board=odroid-n2plus

kernel_version=$(pacman -Qi linux | grep Version | cut -d: -f2 | xargs)
kernel_major=$(echo ${kernel_version} | cut -d. -f1)
kernel_minor=$(echo ${kernel_version} | cut -d. -f2)

boot_ini=""
boot_ini_version=""
if [ $kernel_major -gt 4 ]; then
    boot_ini=/usr/share/uboot-${board}/boot.mainline.ini
    boot_ini_version="mainline"
else
    boot_ini=/usr/share/uboot-${board}/boot.hardkernel.ini
    boot_ini_version="hardkernel"
fi

if [ -e /boot/boot.ini ]; then
    if ! grep "KERNEL: ${boot_ini_version}" /boot/boot.ini > /dev/null ; then
        mv /boot/boot.ini "/boot/boot.ini.$(date +"%s")"
        cp $boot_ini /boot/boot.ini
    fi
else
    cp $boot_ini /boot/boot.ini
fi

# Add proper UUID to boot.ini
major=$(mountpoint -d / | cut -f 1 -d ':')
minor=$(mountpoint -d / | cut -f 2 -d ':')
device=$(cat /proc/partitions | awk {'if ($1 == "'${major}'" && $2 == "'${minor}'") print $4 '})
device_uuid=$(lsblk -o uuid,name | grep ${device} | awk "{print \$1}")

sed -i "s/root=\/dev\/mmcblk\${devno}p2/root=UUID=${device_uuid}/g" \
    /boot/boot.ini
