#!/bin/bash

PATH="/sbin:/usr/sbin:/bin:/usr/bin:$PATH"

board=odroid-c4

kernel_version=$(pacman -Qi linux | grep Version | cut -d: -f2 | xargs)
kernel_major=$(echo ${kernel_version} | cut -d. -f1)
kernel_minor=$(echo ${kernel_version} | cut -d. -f2)

boot_ini=""
boot_ini_version=""
if [ $kernel_major -gt 4 ]; then
    boot_ini=/usr/share/uboot-${board}/boot.mainline.ini
    boot_ini_version="mainline"
else
    boot_ini=/usr/share/uboot-${board}/boot.hardkernel.ini
    boot_ini_version="hardkernel"
fi

if [ -e /boot/boot.ini ]; then
    if ! grep "KERNEL: ${boot_ini_version}" /boot/boot.ini > /dev/null ; then
        mv /boot/boot.ini "/boot/boot.ini.$(date +"%s")"
        cp $boot_ini /boot/boot.ini
    fi
else
    cp $boot_ini /boot/boot.ini
fi

model=""
if [ -e /sys/devices/soc0/machine ]; then
  model="$(cat /sys/devices/soc0/machine | sed "s/Hardkernel //g")"
elif [ -e /sys/firmware/devicetree/base/model ]; then
  model="$(cat /sys/firmware/devicetree/base/model | sed "s/Hardkernel //g")"
fi

if [ "$model" = "ODROID-HC4" ]; then
    if [ -e /boot/dtbs/amlogic/meson64_odroidhc4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-odroid-hc4\.dtb/\/dtbs\/amlogic\/meson64_odroidhc4\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson-sm1-odroid-hc4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_odroidhc4\.dtb/\/dtbs\/amlogic\/meson-sm1-odroid-hc4\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson64_odroidc4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-odroid-hc4\.dtb/\/dtbs\/amlogic\/meson64_odroidc4\.dtb/g" \
            /boot/boot.ini
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-odroid-c4\.dtb/\/dtbs\/amlogic\/meson64_odroidc4\.dtb/g" \
            /boot/boot.ini
        echo "Warning: Using odroidc4 dtb on odroidhc4"
    elif [ -e /boot/dtbs/amlogic/meson-sm1-odroid-c4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_odroidhc4\.dtb/\/dtbs\/amlogic\/meson-sm1-odroid-c4\.dtb/g" \
            /boot/boot.ini
        sed -i "s/\/dtbs\/amlogic\/meson64_odroidc4\.dtb/\/dtbs\/amlogic\/meson-sm1-odroid-c4\.dtb/g" \
            /boot/boot.ini
        echo "Warning: Using odroidc4 dtb on odroidhc4"
    else
        echo "Error: The kernel you installed doesn't seems to support the odroidhc4"
    fi
else
    if [ -e /boot/dtbs/amlogic/meson64_odroidc4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-odroid-c4\.dtb/\/dtbs\/amlogic\/meson64_odroidc4\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson-sm1-odroid-c4.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_odroidc4\.dtb/\/dtbs\/amlogic\/meson-sm1-odroid-c4\.dtb/g" \
            /boot/boot.ini
    else
        echo "Error: The kernel you installed doesn't seems to support the odroidc4"
    fi
fi

# Handle root device of installations running on external usb drive
major=$(mountpoint -d / | cut -f 1 -d ':')
minor=$(mountpoint -d / | cut -f 2 -d ':')
device=$(cat /proc/partitions | awk {'if ($1 == "'${major}'" && $2 == "'${minor}'") print $4 '})
device="\/dev\/${device}"

if ! (echo "$device" | grep "mmcblk" > /dev/null) ; then
    if ! (echo "$device" | grep "loop" > /dev/null) ; then
        sed -i "s/root=\/dev\/mmcblk\${devno}p2/root=${device}/g" \
            /boot/boot.ini
    fi
fi
